# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
