# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('foto', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='categoria',
            field=models.CharField(default='LAZER', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='atividade',
            name='prioridade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atividade',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplicacao.Usuario'),
            preserve_default=False,
        ),
    ]
