# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_auto_20160310_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='_foto',
            field=models.TextField(blank=True),
        ),
    ]
