# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_atividade_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='prioridade',
            field=models.BooleanField(default=False),
        ),
    ]
