# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0004_auto_20160315_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='foto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
