# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0005_auto_20160315_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='categoria',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
