# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0005_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplicacao.Usuario'),
            preserve_default=False,
        ),
    ]
