# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0006_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='tag_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aplicacao.Tag'),
        ),
    ]
