# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0006_auto_20160316_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='categoria',
            field=models.CharField(max_length=14),
        ),
    ]
