# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0007_atividade_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='atividade',
            name='tags',
            field=models.ManyToManyField(to='aplicacao.Tag'),
        ),
    ]
