# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0008_auto_20160315_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='nome',
            new_name='tag_nome',
        ),
    ]
