# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0008_auto_20160317_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='nome',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
