# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0008_auto_20160310_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto_url',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.CharField(max_length=100),
        ),
    ]
