# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0009_auto_20160317_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.Atividade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.Usuario')),
            ],
        ),
    ]
