# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0010_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
