# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0011_auto_20160316_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATIVIDADE_TAG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Atvidade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.Atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tag', models.CharField(blank=True, max_length=14)),
            ],
        ),
        migrations.AddField(
            model_name='atividade_tag',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.Tag'),
        ),
    ]
